src/carts/urls.py
# coding=utf-8
from django.conf.urls import url


from .views import (
    cart_home,
    cart_update,
    checkout_home,
    checkout_done_view
)

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^update/$', cart_update, name='update'),
]

src/ecommerce/urls.py
# coding=utf-8
"""
HyperNova URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static

from accounts.views import login_page, register_page, guest_register_page
from carts.views import cart_detail_api_view
from addresses.views import checkout_address_create_view, checkout_address_reuse_view

from .views import (
    home_page,
    about_page,
    contact_page
)

urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^about/$', about_page, name='about'),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^login/$', login_page, name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^api/cart/$', cart_detail_api_view, name='api-cart'),
    url(r'^cart/', include('carts.urls', namespace='cart')),
    url(r'^register/$', register_page, name='register'),
    url(r'^register/guest/$', guest_register_page, name='guest_register'),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
# coding=utf-8
from django.conf.urls import url


from .views import (
    ProductListView,
    ProductDetailSlugView
)

urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),
]

src/templates/base/css.html
{% load static %}

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static "css/site_compliment.css" %}">

<!--Font awesome CSS-->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
      integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"
      crossorigin="anonymous">

<!--JQuery Confirm-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">

src/templates/base/footer.html
{% load static %}

<div class="container-fluid">
    <div class="row align-items-start row-color-hd text-white h-220">
        <div class="col col-md-1">
        </div>
        <div class="col-md-3 mt-2 text-center">
            <img src="{% static 'img/logo-white.png' %}" height="78px" width="206px" alt=""/>
            <p class="pr-4 pl-4 text-justify">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </p>
            <br/>
            <div class="container-fluid">
                <div class="row w-100 align-items-middle">
                    <div class="col col-md-2">
                    </div>
                    <div class="col-sm-2 text-center">
                        <a target="_blank" rel="noopener" class="social-footer" href="https://www.facebook.com/mirumeelabs/">
                            <img src="{% static 'img/facebook-logo.svg' %}" width="25px" height="25px" alt=""/>
                        </a>
                    </div>
                    <div class="col-sm-2 text-center">
                        <a target="_blank" rel="noopener" class="social-footer" href="https://twitter.com/getsaleor">
                            <img src="{% static 'img/twitter-logo.svg' %}" width="25px" height="25px" alt=""/>
                        </a>
                    </div>
                    <div class="col-sm-2 text-center">
                        <a target="_blank" rel="noopener" class="social-footer" href="https://plus.google.com/+Mirumee">
                            <img src="{% static 'img/google-logo.svg' %}" width="25px" height="25px" alt=""/>
                        </a>
                    </div>
                    <div class="col-sm-2 text-center">
                        <a target="_blank" rel="noopener" class="social-footer" href="https://www.instagram.com/explore/tags/mirumee/">
                            <img src="{% static 'img/instagram-logo.svg' %}" width="25px" height="25px" alt=""/>
                        </a>
                    </div>
                    <div class="col col-md-1">
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2 mt-2 text-center">
            <h3>Navegaci&oacute;n</h3>
            <br/>
            <ul class="ft-ul-title">
                <li>Perfumes</li>
                <li>Tecnologia</li>
                <li>Relojes</li>
            </ul>
        </div>
        <div class="col-md-2 mt-2 text-center">
            <h3>Mi Cuenta</h3>
            <br/>
            <ul class="ft-ul-title">
                <li>Tu Carro</li>
                <li>Registrarse</li>
                <li>Iniciar Sesion</li>
            </ul>
        </div>
        <div class="col-md-3 mt-2 text-center">
            <h3>Metodos de Pago</h3>
            <br/>
            <p class="pr-4 pl-4 text-justify">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            </p>
            <div class="container-fluid">
                <div class="row w-100 align-items-middle">
                    <div class="col col-md-2">
                    </div>
                    <div class="col-sm-2 text-center">
                        <img src="{% static 'img/visa.png' %}" width="45px" height="40px" alt=""/>
                    </div>
                    <div class="col-sm-2 text-center">
                        <img src="{% static 'img/mastercard.png' %}" width="45px" height="40px" alt=""/>
                    </div>
                    <div class="col-sm-2 text-center">
                        <img src="{% static 'img/american.png' %}" width="45px" height="40px" alt=""/>
                    </div>
                    <div class="col-sm-2 text-center">
                        <img src="{% static 'img/discover.png' %}" width="45px" height="40px" alt=""/>
                    </div>
                    <div class="col col-md-1">
                    </div>
                </div>
            </div>
        </div>
        <div class="col col-md-1">
        </div>
    </div>

    <div class="row row-color-hd text-white pt-3 align-items-middle ft-copryght">
        <div class="col col-md-1">
        </div>
        <div class="col-md-5">
            @2018 HYPERNOVA. TODOS LOS DERECHOS RESERVADOS.
        </div>
        <div class="col-md-5 text-right">
            TÉRMINOS Y CONDICIONES &nbsp; | &nbsp; POLÍTICA DE PRIVACIDAD &nbsp; | &nbsp; ACERCA DE &nbsp;
        </div>
        <div class="col col-md-1">
        </div>
    </div>

</div>

src/templates/base/js.html
{% load static %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>

<!-- JQuery Confirm -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>

<!-- Django Secure AJAX JS -->
<script src="{% static 'js/csrf.ajax.js' %}"></script>

<!-- eCommerce Custom JS -->
<script src="{% static 'js/site_compliment.js' %}"></script>

src/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as product_list_url%}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'cart:home' as cart_url %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
    <div class="container">
        <a class="navbar-brand" href="{{ home_url }}">

            {% if brand_name %} {{ brand_name }} {% else %} HyperNova {% endif %}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if request.path == home_url %} active {% endif %}">
                    <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item {% if request.path == contact_url %} active {% endif %}">
                    <a class="nav-link" href="{{ contact_url }}">Contactanos</a>
                </li>
                <li class="nav-item {% if request.path == product_list_url %} active {% endif %}">
                    <a class="nav-link" href="{{ product_list_url }}">Productos</a>
                </li>
            {% if request.user.is_authenticated %}
                <li class="nav-item {% if request.path == logout_url %} active {% endif %}">
                    <a class="nav-link" href="{{ logout_url }}">Cerrar sesión</a>
                </li>
            {% else %}
                <li class="nav-item {% if request.path == login_url %} active {% endif %}">
                    <a class="nav-link" href="{{ login_url }}">Iniciar sesión</a>
                </li>
                <li class="nav-item {% if request.path == register_url %} active {% endif %}">
                    <a class="nav-link" href="{{ register_url }}">Registrarse</a>
                </li>
            {% endif %}
                <li class="nav-item {% if request.path == cart_url %} active {% endif %}">
                    <a class="nav-link" href="{{ cart_url }}"><span class="navbar-cart-count">
                        {{ request.session.cart_items }}</span> <i class="fas fa-shopping-cart"></i></a>
                </li>

            </ul>
            {% include 'search/snippets/search-form.html' %}
        </div>
    </div>
</nav>

src/templates/base/navbar2.html
{%  load static %}

{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'cart:home' as cart_url %}
{% url 'products:list' as product_list_url%}

<header>
    <div class="container-fluid h-50">
        <div class="row align-items-start row-color-hd text-white">
            <div class="col col-md-1">
            </div>
            <div class="col col-md-6 mt-2">
                CONTACTO TELEFONICO: +593 98 539 4890
            </div>
            <div class="col col-md-5 mt-2 text-center">
                {% if request.user.is_authenticated %}
                    <a class="a-language" href="{{ logout_url }}">Cerrar sesión</a>
                {% else %}
                    <a class="a-language" href={{ register_url }}>Registrarse</a>  &nbsp;&nbsp;&nbsp;<a class="a-language" href={{ login_url }}>Iniciar Sesión</a>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="container-fluid h-75">
        <div class="row w-100 align-items-middle">
            <div class="col col-md-1">
            </div>
            <div class="col col-md-1 mt-4 pt-2 pl-5 text-center">

                <div class="dropdown">
                    <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img src="{% static 'img/logo-menu.png' %}" height="40px" width="30px" alt="">
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{{ product_list_url }}">Todos</a>
                        <a class="dropdown-item" href="#">Tecnología</a>
                        <a class="dropdown-item" href="#">Perfumes</a>
                        <a class="dropdown-item" href="#">Relojes</a>
                    </div>
                </div>

            </div>
            <div class="col-md-2 mt-4 mr-4 text-left">
                <a href="{{ home_url }}">
                    <img src="{% static 'img/logo.png' %}" height="85px" width="230px" alt="">
                </a>
            </div>
            <div class="col-md-5 text-center">
                {% include 'search/snippets/search-form.html' %}
            </div>
            <div class="col-md-2 text-left ml-5">
                <a class="item-cart" id="cart">
                    <span class="notify-badge">{{ request.session.cart_items }}</span>
                    <img src="{% static 'img/cart.png' %}" class="mt-5" width="48" height="50" alt=""/>
                </a>
                <div class="container-cart">
                    <div class="shopping-cart">
                        {% if cart.products.exists %}
                            <div class="shopping-cart-header">
                                <div class="shopping-cart-total">
                                    <span class="lighter-text">Total:</span>
                                    <span class="main-color-text sct">{{ cart.total }}</span>
                                </div>
                            </div>

                            {% for product in cart.products.all %}
                                <ul class="shopping-cart-items">
                                    <li class="clearfix">
                                        <img src="{{ product.image.url }}" width="70" height="70" alt=""/>
                                        <span class="item-name">{{ product.title }}</span>
                                        <span class="item-price">{{ product.price }}</span>
    {#                                    <span class="item-quantity"></span>#}
                                    </li>

                                </ul>
                            {% endfor %}
                            <a href="{{ cart_url }}" class="button-cart">Pago</a>
                        {% else %}
                            <span class="lead">Carreta vacia</span>
                        {% endif %}

                    </div> <!--end shopping-cart -->
                </div> <!--end container -->
            </div>
            <div class="col col-md-1">
            </div>
        </div>
    </div>
</header>