src/carts/urls.py
# coding=utf-8
from django.conf.urls import url


from .views import (
    cart_home,
    cart_update,
    checkout_home,
    checkout_done_view
)

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^update/$', cart_update, name='update'),
]

src/ecommerce/urls.py
# coding=utf-8
"""
HyperNova URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static

from accounts.views import login_page, register_page, guest_register_page
from carts.views import cart_detail_api_view
from addresses.views import checkout_address_create_view, checkout_address_reuse_view

from .views import (
    home_page,
    about_page,
    contact_page
)

urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^about/$', about_page, name='about'),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^login/$', login_page, name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^api/cart/$', cart_detail_api_view, name='api-cart'),
    url(r'^cart/', include('carts.urls', namespace='cart')),
    url(r'^register/$', register_page, name='register'),
    url(r'^register/guest/$', guest_register_page, name='guest_register'),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/carts/models.py
# coding=utf-8
from math import fsum
from django.db import models

from django.conf import settings
from products.models import Product
from django.db.models.signals import pre_save, m2m_changed

User = settings.AUTH_USER_MODEL


class CartManager(models.Manager):
    def new_or_get(self, request):
        """
        Revisa si el Cart ya existe.
        Si no existe, es creado
        :param request: request
        :return: objeto, creado
        """
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            created = False
            obj = qs.first()
            if request.user.is_authenticated() and obj.user is None:
                obj.user = request.user
                obj.save()
        else:
            obj = self.new(user=request.user)
            created = True
            request.session['cart_id'] = obj.id

        return obj, created

    def new(self, user=None):
        """
        Revisa si el usario es autentico
        :param user: usuario, sino None
        :return: objeto de cart del usuario
        """
        user_obj = None
        if user is not None:
            if user.is_authenticated():
                user_obj = user
        return self.model.objects.create(user=user_obj)


class Cart(models.Model):
    user        = models.ForeignKey(User, null=True, blank=True)
    products    = models.ManyToManyField(Product, blank=True)
    subtotal    = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total       = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    iva         = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    updated     = models.DateTimeField(auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)

    objects = CartManager()  # extiende las funciones de objects

    def __str__(self):
        return str(self.id)


def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    """
    Suma los valores de los productos que son añadidos a la carreta
    :param sender: sender
    :param instance: instancia actual
    :param action: action
    :param args: args
    :param kwargs: kwargs
    """
    actions = ['post_add', 'post_remove', 'post_clear']
    if action in actions:
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        if instance.subtotal != total:
            instance.subtotal = format(total, '.2f')
            instance.save()


m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)


def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    """
    Calcula el iva y lo añade a la suma total de la carreta
    :param sender: sender
    :param instance: instancia actual
    :param args: args
    :param kwargs: kwargs
    """
    if float(instance.subtotal) > 0:
        iva = float(instance.subtotal) * 0.12
        instance.iva = format(iva, '.2f')
        new_total = fsum([float(instance.subtotal), iva])
        instance.total = format(new_total, '.2f')
    else:
        instance.total = 0.00


pre_save.connect(pre_save_cart_receiver, sender=Cart)

src/carts/views.py
# coding=utf-8
from django.http import JsonResponse
from django.shortcuts import render, redirect

from accounts.forms import LoginForm, GuestForm
from addresses.forms import AddressForm
from addresses.models import Address
from billing.models import BillingProfile
from orders.models import Order
from .models import Cart
from products.models import Product


def cart_detail_api_view(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    products = [{
        "id": x.id,
        "url": x.get_absolute_url(),
        "title": x.title,
        "price": x.price
        }
        for x in cart_obj.products.all()]
    cart_data = {"products": products, "subtotal": cart_obj.subtotal, "iva": cart_obj.iva, "total": cart_obj.total}
    return JsonResponse(cart_data)

def cart_home(request):
    """
    Crea un objeto de tipo Cart donde se van a
    guardar los productos elegidos por el usuario
    :param request: request
    :return: objecto cart
    """
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    return render(request, "carts/home.html", {'cart': cart_obj})


def cart_update(request):
    """
    Actualiza la carreta con los productos que el usario elige
    puede añadir o eliminar productos de la carreta
    :param request: request
    :return: producto añadido o eliminado y retorna a home
    """
    product_id = request.POST.get('product_id')

    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)  # lo busca por id
        except Product.DoesNotExist:
            return redirect("cart:home")

        cart_obj, new_obj = Cart.objects.new_or_get(request)  # revisa si el producto ya esta o es nuevo

        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)  # si ya se encuentra en la carreta lo elimina
            added = False
        else:
            cart_obj.products.add(product_obj)  # si no se encuentra en la carreta lo añade
            added = True
        request.session['cart_items'] = cart_obj.products.count()  # suma la cantidad de productos en la carreta

        if request.is_ajax():  # Asynchronous JavaScript And XML
            json_data = {
                "added": added,
                "removed": not added,
                "cartItems": cart_obj.products.count()
            }
            return JsonResponse(json_data)
    return redirect("cart:home")


def checkout_home(request):
    """
    Obtiene todos los datos adquiridos del usuario
    profile, direccion de entrega y pago, y crea una orden
    :param request: request
    :return: total con los datos del usuario
    """
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0:
        return redirect("cart:home")

    login_form = LoginForm()  # en el checkout el usuario puede hacer login si ya creo una cuenta
    guest_form = GuestForm()  # el usuario puede hacer checkout como guest
    address_form = AddressForm()
    pago_address_id = request.session.get("pago_address_id", None)  # direccion actual del usuario
    entrega_address_id = request.session.get("entrega_address_id", None)  # direccion de entrega

    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
    address_qs = None
    if billing_profile is not None:
        if request.user.is_authenticated():
            address_qs = Address.objects.filter(billing_profile=billing_profile)

        order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)
        if entrega_address_id:
            order_obj.shipping_address = Address.objects.get(id=entrega_address_id)
            del request.session["entrega_address_id"]
        if pago_address_id:
            order_obj.billing_address = Address.objects.get(id=pago_address_id)
            del request.session["pago_address_id"]
        if entrega_address_id or pago_address_id:
            order_obj.save()

    # Si el usuario ya pago, la carreta se vacia y el orden cambia a pagado
    if request.method == "POST":
        if order_obj.mark_paid() == 'pagado':
            request.session['cart_items'] = 0
            del request.session['cart_id']
            return redirect("cart:success")

    context = {
        "object": order_obj,
        "billing_profile": billing_profile,
        "login_form": login_form,
        "guest_form": guest_form,
        "address_form": address_form,
        "address_qs": address_qs,
    }

    return render(request, "carts/checkout.html", context)


def checkout_done_view(request):
    """
    Finalizada la compra el usuario es dirigido a la pagina de terminado
    :param request: request
    :return: pagina de terminado
    """
    return render(request, "carts/checkout-done.html", {})

src/carts/templates/carts/checkout-done.html
{% extends 'base.html' %}

{% block content %}

    <div class="col-6 mx-auto py-5 text-center">

        <h1 class="display-1">Gracias por su compra!</h1>

    </div>

{% endblock %}

src/carts/templates/carts/checkout.html
{% extends "base.html" %}

{% block content %}

    {% if not billing_profile %}
        <div class="row text-center">
            <div class="col-12 col-md-6">
                <p class="lead">Login</p>
                {% include 'accounts/snippets/form.html' with form=login_form next_url=request.build_absolute_uri %}
            </div>
            <div class="col-12 col-md-6">
                Continue as Guest
                {% url 'guest_register' as guest_register_url %}
                {% include 'accounts/snippets/form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url %}

            </div>
        </div>

    {% else %}
        {% if not object.shipping_address %}
            <div class="row">
                <div class="col-12">
                    <p class="lead">Direccion de Envio</p>
                    <hr/>
                </div>
                <div class="col-6">

                        {% url "checkout_address_create" as checkout_address_create %}
                        {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='entrega' %}

                </div>
                <div class="col-6">
                    {% url 'checkout_address_reuse' as checkout_address_reuse %}
                    {% include 'addresses/prev_addresses.html' with address_qs=address_qs next_url=request.build_absolute_uri address_type='entrega' action_url=checkout_address_reuse %}
                </div>
            </div>

        {% elif not object.billing_address %}

            <div class="row">
                <div class="col-12">
                    <p class="lead">Direccion de Pago</p>
                    <hr/>
                </div>
                <div class="col-6">
                    {% url "checkout_address_create" as checkout_address_create %}
                    {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='pago' %}
                </div>

                <div class="col-6">
                    {% url 'checkout_address_reuse' as checkout_address_reuse %}
                    {% include 'addresses/prev_addresses.html' with address_qs=address_qs next_url=request.build_absolute_uri address_type='pago' action_url=checkout_address_reuse %}
                </div>

            </div>
        {% else %}

            <h1>Checkout</h1>

            <p>Carreta: {% for p in object.cart.products.all %}{{ p }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
            <p>Direccion de entrega: {{ object.shipping_address.get_address }}</p>
            <p>Direccion de pago: {{ object.billing_address.get_address }}</p>
            <p>Total de la carreta: {{ object.cart.total }}</p>
            <p>Costo de envio: {{ object.shipping_total }}</p>
            <p>Orden total: {{ object.order_total }}</p>
            <form class="form" method="POST" action="">
            {% csrf_token %}
                <button type="submit" class="btn btn-success">Finalizar</button>
            </form>


        {% endif %}

    {% endif %}

{% endblock %}

src/carts/templates/carts/home.html
{% extends 'base.html' %}


{% block content %}

<h1>Carreta</h1>
    {% if cart.products.exists %}
    <table class="table cart-table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nombre</th>
            <th scope="col">Precio</th>
        </tr>
        </thead>
        <tbody class="cart-body">
                {% for product in cart.products.all %}
                <tr class="cart-product">
                    <th scope="row">{{ forloop.counter }}</th>
                    <td><a href="{{ product.get_absolute_url }}">{{ product.title }}</a>

                    {% include 'carts/snippets/remove-product.html' with product_id=product.id %}

                    </td>
                    <td>{{ product.price }}</td>

                </tr>
                {% endfor %}
            <tr>
                <td colspan="2"></td>
                <td><b>Subtotal</b>$<span class="cart-subtotal"> {{ cart.subtotal }}</span></td>
            </tr>
            <tr>
                <td colspan="2"></td>
                <td><b>Iva (12%)</b>$<span class="cart-iva"> {{ cart.iva }}</span></td>
            </tr>
            <tr>
                <td colspan="2"></td>
                <td><b>Total</b>$<span class="cart-total"> {{ cart.total }}</span></td>
            </tr>
            <tr>
                <td colspan="2"></td>
                <td><a class="btn btn-lg btn-success" href="{% url 'cart:checkout' %}">Checkout</a></td>
            </tr>
        </tbody>
    </table>

        <div class="cart-item-remove-form" style="display: none">
            {% include 'carts/snippets/remove-product.html' %}
        </div>
    {% else %}
    <p class="lead">Carreta vacia</p>
    {% endif %}


{% endblock %}